
db_host              = ""
db_password          = ""
db_user              = "dbuser"
db_name              = "openproject_db"
s3_bucket            = ""
s3_access_key        = ""
s3_secret_key        = ""
s3_region            = "us-east-1"
hostname             = ""
smtp_host            = "smtp.gmail.com"
smtp_user            = "jaynaj79.gmail.com"
smtp_pasmtp_password = ""
storage_size         = "20Gi"
storage_class        = ""
